### ISSUE TITLE
Improve the Performance of the website

### ISSUE THREAD

**Issue by akshatnema** [BitByte-TPC/hackbyte#17]
### Description
The Performance of the website is poorly affected due to the initial loading of the animations provided in the homepage. Try to reduce the size of animation in any way to make the performance of the website at the normal level.

![Screenshot from 2023-01-20 00-11-31](https://user-images.githubusercontent.com/76521428/213532237-0e1b4151-c447-4232-a05a-e3b1129ca2a4.png)

![Screenshot from 2023-01-20 00-11-50](https://user-images.githubusercontent.com/76521428/213532255-42b68dd2-8c27-4111-9916-d4ae8dc0438c.png)

Source: Lighthouse report from Neltify

**Comment by prajjwalkapoor** [comment]
closed with #24 
![image](https://user-images.githubusercontent.com/68912239/215183226-10ee0973-c988-48f0-83b6-336dd2b9aa69.png)
