### ISSUE TITLE
Improve the visibility of text in mobile view

### ISSUE THREAD

**Issue by akshatnema** [BitByte-TPC/hackbyte#18]
### Description
Currently, the big headers/headlines in the website become extremely small in the mobile view and thus decreases the user readability and experience through the website via mobile. Make the fonts in terms of `rem` units to improve in the mobile view.

Preview:
![image](https://user-images.githubusercontent.com/76521428/213533505-9bc1c936-051a-4a13-b18e-869e760e0cb2.png)

**Comment by prajjwalkapoor** [comment]
Fixes #22
