### ISSUE TITLE
Make header sticky on scroll

### ISSUE THREAD

**Issue by prajjwalkapoor** [BitByte-TPC/hackbyte#23]
When scrolling through the website, the header should be sticky and the background should be with glassmorphismic effect.

For reference:
Design: [https://mdbootstrap.com/snippets/standard/mdbootstrap/4686783](https://mdbootstrap.com/snippets/standard/mdbootstrap/4686783)
Implementation: [https://www.w3schools.com/howto/howto_js_sticky_header.asp](https://www.w3schools.com/howto/howto_js_sticky_header.asp)

**Comment by sahilarora02** [comment]
Is the feature still on the table for implementation? I'm interested in contributing to it.

Thanks!
@mittalvansh

**Comment by mittalvansh** [comment]
We are not currently working on the mentioned feature.
@sahilarora02
